# TODO:// Rollen passierende ApiEndpoints nach Service aufgeteilt

http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  everyoneUser: # Beschreibung für Policies
    host: '*' # required, '*' will not check for host name
    paths: # Array mit allen Endpoints die jeder Erreichen darf
      - '/ip'
      - '/getUser/*'
      - '/profile/*'
    methods: ['GET', 'OPTIONS', 'POST']
  everyoneSchedule: # Endpoints die nur von Fahrlehrer erreicht werden dürfen
    host: '*'
    paths:
      - 'checkSchedule'
    methods: ['GET', 'OPTIONS', 'POST']
  everyoneAppointment:
    host: '*'
    paths:
      - '/checkAppointment/*'
      - '/getAppointment/*'
serviceEndpoints:
  user:
    url: 'https://httpbin.org/'
  appointment:
    url: 'https://httpbin.org/'
  schedule:
    url: 'https://httpbin.org/'
    ##
    ##
    ## Policies
    ##
policies:
  - jwt-header
  - proxy
##
##
## Regeln
##
pipelines:
  - name: everyoneUser
    apiEndpoints:
      - everyoneUser
    policies:
      - jwt-header:
          - action: # everything under the action will be actionParams
              role: 'everyone'
      - proxy: # policy name
          - action:
              serviceEndpoint: user # see declaration above
  - name: everyoneSchedule
    apiEndpoints:
      - everyoneSchedule
    policies:
      - jwt-header:
          - action: # everything under the action will be actionParams
              role: 'everyone'
      - proxy: # policy name
          - action:
              serviceEndpoint: schedule # see declaration above
  - name: everyoneAppointment
    apiEndpoints:
      - everyoneAppointment
    policies:
      - jwt-header:
          - action:
              role: 'everyone'
      - proxy:
          - action:
              serviceEndpoint: appointment
